name: CICD Setup
description: 'Set up the CI/CD environment for FreeGSNKE'

inputs:
  python-version:
    description: 'Python version used by the job'
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install freegsnke and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[freegs4e,dev,docs]"
      shell: bash
